/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AppAppIdRouteImport } from './routes/app.$appId'
import { Route as ApiPublicBuildCallbackRouteImport } from './routes/api/public/build-callback'
import { Route as ApiPublicNotificationsDispatchRouteImport } from './routes/api/public/notifications-dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdRoute = AppAppIdRouteImport.update({
  id: '/app/$appId',
  path: '/app/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildCallbackRoute = ApiPublicBuildCallbackRouteImport.update({
  id: '/api/public/build-callback',
  path: '/api/public/build-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsDispatchRoute =
  ApiPublicNotificationsDispatchRouteImport.update({
    id: '/api/public/notifications-dispatch',
    path: '/api/public/notifications-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/app/$appId': typeof AppAppIdRoute
  '/api/public/build-callback': typeof ApiPublicBuildCallbackRoute
  '/api/public/notifications-dispatch': typeof ApiPublicNotificationsDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/app/$appId': typeof AppAppIdRoute
  '/api/public/build-callback': typeof ApiPublicBuildCallbackRoute
  '/api/public/notifications-dispatch': typeof ApiPublicNotificationsDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/dev': typeof DevRoute
  '/app/$appId': typeof AppAppIdRoute
  '/api/public/build-callback': typeof ApiPublicBuildCallbackRoute
  '/api/public/notifications-dispatch': typeof ApiPublicNotificationsDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/dev'
    | '/app/$appId'
    | '/api/public/build-callback'
    | '/api/public/notifications-dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/dev'
    | '/app/$appId'
    | '/api/public/build-callback'
    | '/api/public/notifications-dispatch'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categories'
    | '/dev'
    | '/app/$appId'
    | '/api/public/build-callback'
    | '/api/public/notifications-dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  DevRoute: typeof DevRoute
  AppAppIdRoute: typeof AppAppIdRoute
  ApiPublicBuildCallbackRoute: typeof ApiPublicBuildCallbackRoute
  ApiPublicNotificationsDispatchRoute: typeof ApiPublicNotificationsDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId': {
      id: '/app/$appId'
      path: '/app/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof AppAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-callback': {
      id: '/api/public/build-callback'
      path: '/api/public/build-callback'
      fullPath: '/api/public/build-callback'
      preLoaderRoute: typeof ApiPublicBuildCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications-dispatch': {
      id: '/api/public/notifications-dispatch'
      path: '/api/public/notifications-dispatch'
      fullPath: '/api/public/notifications-dispatch'
      preLoaderRoute: typeof ApiPublicNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  DevRoute: DevRoute,
  AppAppIdRoute: AppAppIdRoute,
  ApiPublicBuildCallbackRoute: ApiPublicBuildCallbackRoute,
  ApiPublicNotificationsDispatchRoute: ApiPublicNotificationsDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
